---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: jenkins-rs-limits
  labels:
    app: jenkins
spec: 
  minReadySeconds: 3
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
      env: dev
  template:
    metadata: 
      name: jenkins-pod  
      labels:
        app: jenkins
        env: dev
    spec:
      containers:
        - name: jenkins-cont
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"

    