---
apiVersion: apps/v1
kind: ReplicaSet
metadata:   
  name: jenkins-pod
  labels: 
    app: jenkins
spec:
  minReadySeconds: 3
  replicas: 2
  selector: 
    matchLabels: 
      app: jenkins
  template: 
    metadata:
      labels: 
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
              protocol: TCP
      initContainers: 
        - name: alpine
          image: alpine
          command: ["ping", "-c", "4", "google.com"]
      restartPolicy: Never
