---
apiVersion: v1 
kind: Pod
metadata: 
  name: nginx1
  labels:
    app: nginx
    version: "1.23"
spec:
  containers:
    - image: nginx:1.23
      name: nginxone
      ports:
        - containerPort: 80
          protocol: TCP
    
---
apiVersion: v1 
kind: Pod
metadata: 
  name: nginx2
  labels:
    app: nginx
    version: "1.24"
spec:
  containers:
    - image: nginx:1
      name: nginxtwo
      ports:
        - containerPort: 80
          protocol: TCP
      
