---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: test-ng-rc
spec: 
  minReadySeconds: 3
  replicas: 2
  selector:
    app: nginx
    version: "1.23"
  template:
    metadata:
      labels:
        app: nginx
        version: "1.23"
    spec: 
      containers:
        - name: test-ng-rc
          image: nginx:1.23
          ports:  
            - containerPort: 80
              protocol: TCP 