---
apiVersion: batch/v1
kind: Job
metadata:
  name: jobs-demo
  namespace: test-namespace
spec:
  backoffLimit: 4
  manualSelector: true
  selector:
    matchLabels: 
      job: run
  template:
    metadata:
      name: job
      namespace: test-namespace
      labels:
        job: run
    spec:
      restartPolicy: OnFailure
      containers:
        - name: job
          image: alpine:3
          command:    
            - sleep 
            - 30s


