---
apiVersion: v1
kind: Pod
metadata: 
  name: mysql-pod-demo
spec:
  containers:
    - name: my-sql
      image: mysql:8-debian
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: employees
        - name: MYSQL_USER
          value: krishna
        - name: MYSQL_PASSWORD
          value: krishna
      volumeMounts: 
        - mountPath: /var/lib/mysql
          name: mysql-vol
  volumes: 
    - name: mysql-vol
      emptyDir: 


