---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx-rs-demo
  labels:
    app: nginx
    version: "1.0"
spec:   
  minReadySeconds: 3
  replicas: 4
  selector: 
    #matchLabels: 
     # app: nginx
      #version: "1.23"
    matchExpressions:
      - key: app
        operator: In
        values: 
          - nginx
          - apache
  template: 
    metadata: 
      name: something
      labels:
        app: nginx
        version: "1.0"
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - containerPort: 80
              protocol: TCP