---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc 
spec:
    type: ClusterIP
    selector:
      app: nginx
      version: "1.0"
    ports:
      - name: nginx-web-port
        port: 35000
        targetPort: 80 