---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mysql-azure-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests: 
      storage: 1Gi