---
apiVersion: v1
kind: Pod
metadata: 
  name: jenkins-pod
spec: 
  containers: 
    - image: jenkins/jenkins
      name: jenkins
      ports: 
        - containerPort: 8080
          protocol: TCP
    - image: nginx:1.23
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP