---
apiVersion: v1
kind: Secret
metadata:
  name: hello-secret
data:
  username: bWFkYXN1a3Jpc2huYXByYXNhZDU2ODNAZ21haWwuY29t
  password: Y21WbWRHdHVPakF4T2pBd01EQXdNREF3TURBNlVWRlhTblZQUTNkak9VZFVXVk5ZYXpZMVFUVktTVWxPYXpCbg==
  server: amZyb2dmb3J0ZXN0aW5nLmpmcm9nLmlv
  email: bWFkYXN1a3Jpc2huYXByYXNhZDU2ODNAZ21haWwuY29t