---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-mount
spec:   
  containers:
    - name: alpine-cont
      image: alpine:3
      command:
        - sleep 
        - 1d
      volumeMounts:
        - name: mysecrets
          mountPath: /secrets   
  volumes:
    - name: mysecrets
      secret:
        secretName: hello-secret
