---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-mount
spec:   
  imagePullSecrets:
    - name: hello-secretforjfrog
  containers:
    - name: saleor
      image:  jfrogfortesting.jfrog.io/docker-local/madasu/saleor:DEV
      command:
        - sleep 
        - 1d
  #     volumeMounts:
  #       - name: mysecrets
  #         mountPath: /secrets   
  # volumes:
  #   - name: mysecrets
  #     secret:
  #       secretName: hello-secret
  tolerations:  
    - key: krishna
      value: prema
      operator: Equal