---
apiVersion: v1
kind: Secret
metadata:
  name: hello-secret
data:
  username: aws
  password: 388640553654.dkr.ecr.ap-south-1.amazonaws.com
  # server: amZyb2dmb3J0ZXN0aW5nLmpmcm9nLmlv
  # email: bWFkYXN1a3Jpc2huYXByYXNhZDU2ODNAZ21haWwuY29t