---
apiVersion: v1
kind: Pod
metadata:
  name: jfrog-secret
spec:   
  containers:
    - name: nginx-cont
      image: jfrogfortesting.jfrog.io/docker/hello-world:1.0.0
      command:
        - sleep 
        - 1d
      volumeMounts:
        - name: mysecrets
          mountPath: /secrets   
  volumes:
    - name: mysecrets
      secret:
        secretName: hello-secret
  imagePullSecrets:
    - name: mysecrets
