---
apiVersion: v1
kind: Secret
metadata:
  name: test
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJhcmp1bnRlc3QuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogIllYSnFkVzVoZDNOamJHOTFaRUJuYldGcGJDNWpiMjA2UVV0RGNEaHVlVmxFTWtFeVJrRkxTSFp0UWxoR1dVRnpTelEzZG1SNWVXVTBXa1JWU2xKRVlUSXhWSFJaUWt0eGNtaENhSEUxTkRkS1JsSnFkRXRTWW01VFIwcHJjM0J5Wmc9PSIKCQl9Cgl9Cn0=
type: kubernetes.io/.dockerconfigjson 