---
apiVersion: v1
kind: Pod
metadata:   
  name: test
spec:
  imagePullSecrets:
    - name: test
  containers:
    - name: jenkins 
      image: arjuntest.jfrog.io/docker-local/jenkins/jenkins:latest